# Generated by Django 2.1.2 on 2018-10-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='group_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='group_show_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='group_show_size',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='classroom',
            name='group_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='classroom',
            name='lesson',
            field=models.IntegerField(choices=[(1, '基礎程式設計：使用Scratch2.X')], default=0),
        ),
    ]
