# Generated by Django 2.1.2 on 2018-10-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20181015_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='lesson',
            field=models.IntegerField(choices=[(1, '基礎程式設計：使用Scratch2.X')], default=0, verbose_name='課程名稱'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=30, verbose_name='班級名稱'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='password',
            field=models.CharField(max_length=30, verbose_name='選課密碼'),
        ),
    ]
