# Generated by Django 2.1.2 on 2018-10-14 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_visitor_visitorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
                ('hit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_id', models.IntegerField(default=0)),
                ('counter_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('counter_ip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('filename', models.CharField(blank=True, max_length=250, null=True)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(default=0)),
                ('filename', models.TextField()),
                ('before_name', models.TextField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='publication_date',
            new_name='time',
        ),
        migrations.AddField(
            model_name='message',
            name='reader_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagepoll',
            name='classroom_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagepoll',
            name='message_type',
            field=models.IntegerField(default=0),
        ),
    ]
