# Generated by Django 2.1.2 on 2018-10-14 19:28

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('classroom_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='enroll',
            name='group',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enroll',
            name='groupshow',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('student_id', 'classroom_id')},
        ),
    ]
