# Generated by Django 2.1.2 on 2018-10-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20181015_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(default=0)),
                ('enroll_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='EnrollGroup',
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together={('enroll_id', 'group_id')},
        ),
    ]
